// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pix.Infra.Contexts;

namespace Pix.Infra.Migrations
{
    [DbContext(typeof(PixContext))]
    partial class PixContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pix.Domain.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnName("codigo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QuantidadeItens")
                        .HasColumnName("quantidade_itens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d80a981c-cc80-4f44-a879-291eb712650f"),
                            Codigo = "ge01",
                            Nome = "Geovane",
                            QuantidadeItens = 50
                        },
                        new
                        {
                            Id = new Guid("ce2ddcd9-3f0d-4bca-a539-a095c77dd6a4"),
                            Codigo = "ma01",
                            Nome = "Mariane",
                            QuantidadeItens = 10
                        },
                        new
                        {
                            Id = new Guid("285eb121-10e3-4bc9-9275-fad4c83ad42b"),
                            Codigo = "jo01",
                            Nome = "Jonas",
                            QuantidadeItens = 5
                        },
                        new
                        {
                            Id = new Guid("996d3c4d-6be4-4b86-a3f8-1f2d7d0beee6"),
                            Codigo = "cl01",
                            Nome = "Claudia",
                            QuantidadeItens = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
